//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsBlogDataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JsBlogDevelopmentEntities : DbContext
    {
        public JsBlogDevelopmentEntities()
            : base("name=JsBlogDevelopmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
    
        public virtual ObjectResult<usp_GetBlogs_Result> usp_GetBlogs(Nullable<long> startNum, Nullable<long> endNum)
        {
            var startNumParameter = startNum.HasValue ?
                new ObjectParameter("StartNum", startNum) :
                new ObjectParameter("StartNum", typeof(long));
    
            var endNumParameter = endNum.HasValue ?
                new ObjectParameter("EndNum", endNum) :
                new ObjectParameter("EndNum", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetBlogs_Result>("usp_GetBlogs", startNumParameter, endNumParameter);
        }
    }
}
