//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsBlogDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string ProfileImage { get; set; }
        public string Description { get; set; }
        public string Designation { get; set; }
        public string HeadLine { get; set; }
        public Nullable<long> GenderId { get; set; }
    }
}
